const NOT_LOGIN='NOT_LOGIN'
const ERROR_PARAMS='ERROR_PARAMS'
const NOT_REGISTED='NOT_REGISTED'
const INTERNAL_ERROR='INTERNAL_ERROR'
const NO_DATA='NO_DATA'
const ERROR_UPLOAD_IMG='ERROR_UPLOAD_IMG'
const INTERNET_ERROR='INTERNET_ERROR' // 网络错误
const PARAMS_EXCEED='PARAMS_EXCEED'  // 长度限制

module.exports = {
	NOT_LOGIN,
	ERROR_PARAMS,
	NOT_REGISTED,
	INTERNAL_ERROR,
	NO_DATA,
	ERROR_UPLOAD_IMG,
	INTERNET_ERROR,
	PARAMS_EXCEED
}